package com.dcy.pyshop.dao;

import com.dcy.pyshop.entity.CartItem;
import com.dcy.pyshop.entity.CartItemExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface CartItemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cartitem
     *
     * @mbg.generated Sun Sep 23 17:51:01 CST 2019
     */
    long countByExample(CartItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cartitem
     *
     * @mbg.generated Sun Sep 23 17:51:01 CST 2019
     */
    int deleteByExample(CartItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cartitem
     *
     * @mbg.generated Sun Sep 23 17:51:01 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cartitem
     *
     * @mbg.generated Sun Sep 23 17:51:01 CST 2019
     */
    int insert(CartItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cartitem
     *
     * @mbg.generated Sun Sep 23 17:51:01 CST 2019
     */
    int insertSelective(CartItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cartitem
     *
     * @mbg.generated Sun Sep 23 17:51:01 CST 2019
     */
    List<CartItem> selectByExample(CartItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cartitem
     *
     * @mbg.generated Sun Sep 23 17:51:01 CST 2019
     */
    CartItem selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cartitem
     *
     * @mbg.generated Sun Sep 23 17:51:01 CST 2019
     */
    int updateByExampleSelective(@Param("record") CartItem record, @Param("example") CartItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cartitem
     *
     * @mbg.generated Sun Sep 23 17:51:01 CST 2019
     */
    int updateByExample(@Param("record") CartItem record, @Param("example") CartItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cartitem
     *
     * @mbg.generated Sun Sep 23 17:51:01 CST 2019
     */
    int updateByPrimaryKeySelective(CartItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cartitem
     *
     * @mbg.generated Sun Sep 23 17:51:01 CST 2019
     */
    int updateByPrimaryKey(CartItem record);

    CartItem cartItemisExist(@Param("uid") Long uid, @Param("pid") Long pid);

    List<CartItem> allCartItem(Long uid);

    int deleteCartItem(@Param("uid") Long uid, @Param("pid") Long pid);
    int deleteAllCartItem(@Param("uid") Long uid);
}