package com.dcy.pyshop.dao;

import com.dcy.pyshop.entity.Favourite;
import com.dcy.pyshop.entity.FavouriteExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface FavouriteMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table favourite
     *
     * @mbg.generated Fri Oct 05 15:25:03 CST 2019
     */
    long countByExample(FavouriteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table favourite
     *
     * @mbg.generated Fri Oct 05 15:25:03 CST 2019
     */
    int deleteByExample(FavouriteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table favourite
     *
     * @mbg.generated Fri Oct 05 15:25:03 CST 2019
     */
    int deleteByPrimaryKey(Long fid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table favourite
     *
     * @mbg.generated Fri Oct 05 15:25:03 CST 2019
     */
    int insert(Favourite record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table favourite
     *
     * @mbg.generated Fri Oct 05 15:25:03 CST 2019
     */
    int insertSelective(Favourite record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table favourite
     *
     * @mbg.generated Fri Oct 05 15:25:03 CST 2019
     */
    List<Favourite> selectByExample(FavouriteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table favourite
     *
     * @mbg.generated Fri Oct 05 15:25:03 CST 2019
     */
    Favourite selectByPrimaryKey(Long fid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table favourite
     *
     * @mbg.generated Fri Oct 05 15:25:03 CST 2019
     */
    int updateByExampleSelective(@Param("record") Favourite record, @Param("example") FavouriteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table favourite
     *
     * @mbg.generated Fri Oct 05 15:25:03 CST 2019
     */
    int updateByExample(@Param("record") Favourite record, @Param("example") FavouriteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table favourite
     *
     * @mbg.generated Fri Oct 05 15:25:03 CST 2019
     */
    int updateByPrimaryKeySelective(Favourite record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table favourite
     *
     * @mbg.generated Fri Oct 05 15:25:03 CST 2019
     */
    int updateByPrimaryKey(Favourite record);
}