package com.dcy.pyshop.entity;

public class Admin {
    public Admin(Long aid, String username, String password) {
        this.aid = aid;
        this.username = username;
        this.password = password;
    }

    public Admin() {
    }

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.aid
     *
     * @mbg.generated Sat Sep 29 16:20:02 CST 2019
     */
    private Long aid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.username
     *
     * @mbg.generated Sat Sep 29 16:20:02 CST 2019
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.password
     *
     * @mbg.generated Sat Sep 29 16:20:02 CST 2019
     */
    private String password;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.aid
     *
     * @return the value of admin.aid
     *
     * @mbg.generated Sat Sep 29 16:20:02 CST 2019
     */
    public Long getAid() {
        return aid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.aid
     *
     * @param aid the value for admin.aid
     *
     * @mbg.generated Sat Sep 29 16:20:02 CST 2019
     */
    public void setAid(Long aid) {
        this.aid = aid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.username
     *
     * @return the value of admin.username
     *
     * @mbg.generated Sat Sep 29 16:20:02 CST 2019
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.username
     *
     * @param username the value for admin.username
     *
     * @mbg.generated Sat Sep 29 16:20:02 CST 2019
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.password
     *
     * @return the value of admin.password
     *
     * @mbg.generated Sat Sep 29 16:20:02 CST 2019
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.password
     *
     * @param password the value for admin.password
     *
     * @mbg.generated Sat Sep 29 16:20:02 CST 2019
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }
}