package com.dcy.pyshop.entity;

import org.springframework.beans.factory.annotation.Autowired;

public class CartItem {
    @Autowired
    private Product product;

    public Product getProduct() {
        return product;
    }

    @Override
    public String toString() {
        return "CartItem{" +
                "product=" + product +
                ", id=" + id +
                ", uid=" + uid +
                ", pid=" + pid +
                ", buynum=" + buynum +
                ", subtotal=" + subtotal +
                '}';
    }

    public void setProduct(Product product) {
        this.product = product;
    }

    public CartItem(Long id, Long uid, Long pid, Integer buynum, Double subtotal) {
        this.id = id;
        this.uid = uid;
        this.pid = pid;
        this.buynum = buynum;
        this.subtotal = subtotal;
    }

    public CartItem() {
    }

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cartitem.id
     *
     * @mbg.generated Sun Sep 23 17:51:01 CST 2019
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cartitem.uid
     *
     * @mbg.generated Sun Sep 23 17:51:01 CST 2019
     */
    private Long uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cartitem.pid
     *
     * @mbg.generated Sun Sep 23 17:51:01 CST 2019
     */
    private Long pid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cartitem.buyNum
     *
     * @mbg.generated Sun Sep 23 17:51:01 CST 2019
     */
    private Integer buynum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cartitem.subtotal
     *
     * @mbg.generated Sun Sep 23 17:51:01 CST 2019
     */
    private Double subtotal;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cartitem.id
     *
     * @return the value of cartitem.id
     *
     * @mbg.generated Sun Sep 23 17:51:01 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cartitem.id
     *
     * @param id the value for cartitem.id
     *
     * @mbg.generated Sun Sep 23 17:51:01 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cartitem.uid
     *
     * @return the value of cartitem.uid
     *
     * @mbg.generated Sun Sep 23 17:51:01 CST 2019
     */
    public Long getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cartitem.uid
     *
     * @param uid the value for cartitem.uid
     *
     * @mbg.generated Sun Sep 23 17:51:01 CST 2019
     */
    public void setUid(Long uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cartitem.pid
     *
     * @return the value of cartitem.pid
     *
     * @mbg.generated Sun Sep 23 17:51:01 CST 2019
     */
    public Long getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cartitem.pid
     *
     * @param pid the value for cartitem.pid
     *
     * @mbg.generated Sun Sep 23 17:51:01 CST 2019
     */
    public void setPid(Long pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cartitem.buyNum
     *
     * @return the value of cartitem.buyNum
     *
     * @mbg.generated Sun Sep 23 17:51:01 CST 2019
     */
    public Integer getBuynum() {
        return buynum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cartitem.buyNum
     *
     * @param buynum the value for cartitem.buyNum
     *
     * @mbg.generated Sun Sep 23 17:51:01 CST 2019
     */
    public void setBuynum(Integer buynum) {
        this.buynum = buynum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cartitem.subtotal
     *
     * @return the value of cartitem.subtotal
     *
     * @mbg.generated Sun Sep 23 17:51:01 CST 2019
     */
    public Double getSubtotal() {
        return subtotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cartitem.subtotal
     *
     * @param subtotal the value for cartitem.subtotal
     *
     * @mbg.generated Sun Sep 23 17:51:01 CST 2019
     */
    public void setSubtotal(Double subtotal) {
        this.subtotal = subtotal;
    }
}