package com.dcy.pyshop.entity;

public class Category {
    private String belong;

    @Override
    public String toString() {
        return "Category{" +
                "belong='" + belong + '\'' +
                ", cid=" + cid +
                ", cname='" + cname + '\'' +
                ", clevel=" + clevel +
                ", cparentId=" + cparentId +
                '}';
    }

    public String getBelong() {
        return belong;
    }

    public void setBelong(String belong) {
        this.belong = belong;
    }

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column category.cid
     *
     * @mbg.generated Mon Sep 17 08:57:28 CST 2019
     */
    private Long cid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column category.cname
     *
     * @mbg.generated Mon Sep 17 08:57:28 CST 2019
     */
    private String cname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column category.clevel
     *
     * @mbg.generated Mon Sep 17 08:57:28 CST 2019
     */
    private Integer clevel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column category.cparent_id
     *
     * @mbg.generated Mon Sep 17 08:57:28 CST 2019
     */
    private Long cparentId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column category.cid
     *
     * @return the value of category.cid
     *
     * @mbg.generated Mon Sep 17 08:57:28 CST 2019
     */
    public Long getCid() {
        return cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column category.cid
     *
     * @param cid the value for category.cid
     *
     * @mbg.generated Mon Sep 17 08:57:28 CST 2019
     */
    public void setCid(Long cid) {
        this.cid = cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column category.cname
     *
     * @return the value of category.cname
     *
     * @mbg.generated Mon Sep 17 08:57:28 CST 2019
     */
    public String getCname() {
        return cname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column category.cname
     *
     * @param cname the value for category.cname
     *
     * @mbg.generated Mon Sep 17 08:57:28 CST 2019
     */
    public void setCname(String cname) {
        this.cname = cname == null ? null : cname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column category.clevel
     *
     * @return the value of category.clevel
     *
     * @mbg.generated Mon Sep 17 08:57:28 CST 2019
     */
    public Integer getClevel() {
        return clevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column category.clevel
     *
     * @param clevel the value for category.clevel
     *
     * @mbg.generated Mon Sep 17 08:57:28 CST 2019
     */
    public void setClevel(Integer clevel) {
        this.clevel = clevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column category.cparent_id
     *
     * @return the value of category.cparent_id
     *
     * @mbg.generated Mon Sep 17 08:57:28 CST 2019
     */
    public Long getCparentId() {
        return cparentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column category.cparent_id
     *
     * @param cparentId the value for category.cparent_id
     *
     * @mbg.generated Mon Sep 17 08:57:28 CST 2019
     */
    public void setCparentId(Long cparentId) {
        this.cparentId = cparentId;
    }
}