package com.dcy.pyshop.entity;

import java.util.Date;

public class Favourite {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column favourite.fid
     *
     * @mbg.generated Fri Oct 05 15:25:03 CST 2019
     */
    private Long fid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column favourite.uid
     *
     * @mbg.generated Fri Oct 05 15:25:03 CST 2019
     */
    private Long uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column favourite.pid
     *
     * @mbg.generated Fri Oct 05 15:25:03 CST 2019
     */
    private Long pid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column favourite.ftime
     *
     * @mbg.generated Fri Oct 05 15:25:03 CST 2019
     */
    private Date ftime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column favourite.fid
     *
     * @return the value of favourite.fid
     *
     * @mbg.generated Fri Oct 05 15:25:03 CST 2019
     */
    public Long getFid() {
        return fid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column favourite.fid
     *
     * @param fid the value for favourite.fid
     *
     * @mbg.generated Fri Oct 05 15:25:03 CST 2019
     */
    public void setFid(Long fid) {
        this.fid = fid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column favourite.uid
     *
     * @return the value of favourite.uid
     *
     * @mbg.generated Fri Oct 05 15:25:03 CST 2019
     */
    public Long getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column favourite.uid
     *
     * @param uid the value for favourite.uid
     *
     * @mbg.generated Fri Oct 05 15:25:03 CST 2019
     */
    public void setUid(Long uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column favourite.pid
     *
     * @return the value of favourite.pid
     *
     * @mbg.generated Fri Oct 05 15:25:03 CST 2019
     */
    public Long getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column favourite.pid
     *
     * @param pid the value for favourite.pid
     *
     * @mbg.generated Fri Oct 05 15:25:03 CST 2019
     */
    public void setPid(Long pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column favourite.ftime
     *
     * @return the value of favourite.ftime
     *
     * @mbg.generated Fri Oct 05 15:25:03 CST 2019
     */
    public Date getFtime() {
        return ftime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column favourite.ftime
     *
     * @param ftime the value for favourite.ftime
     *
     * @mbg.generated Fri Oct 05 15:25:03 CST 2019
     */
    public void setFtime(Date ftime) {
        this.ftime = ftime;
    }
}