package com.dcy.pyshop.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class History {
    public List<Product> getFootList() {
        return footList;
    }

    public void setFootList(List<Product> footList) {
        this.footList = footList;
    }

    List<Product> footList=new ArrayList<>();

    public Product product;

    public Product getProduct() {
        return product;
    }

    public void setProduct(Product product) {
        this.product = product;
    }

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column history.hid
     *
     * @mbg.generated Tue Oct 02 12:47:03 CST 2019
     */
    private Long hid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column history.uid
     *
     * @mbg.generated Tue Oct 02 12:47:03 CST 2019
     */
    private Long uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column history.pid
     *
     * @mbg.generated Tue Oct 02 12:47:03 CST 2019
     */
    private Long pid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column history.htime
     *
     * @mbg.generated Tue Oct 02 12:47:03 CST 2019
     */
    private Date htime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column history.hid
     *
     * @return the value of history.hid
     *
     * @mbg.generated Tue Oct 02 12:47:03 CST 2019
     */
    public Long getHid() {
        return hid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column history.hid
     *
     * @param hid the value for history.hid
     *
     * @mbg.generated Tue Oct 02 12:47:03 CST 2019
     */
    public void setHid(Long hid) {
        this.hid = hid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column history.uid
     *
     * @return the value of history.uid
     *
     * @mbg.generated Tue Oct 02 12:47:03 CST 2019
     */
    public Long getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column history.uid
     *
     * @param uid the value for history.uid
     *
     * @mbg.generated Tue Oct 02 12:47:03 CST 2019
     */
    public void setUid(Long uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column history.pid
     *
     * @return the value of history.pid
     *
     * @mbg.generated Tue Oct 02 12:47:03 CST 2019
     */
    public Long getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column history.pid
     *
     * @param pid the value for history.pid
     *
     * @mbg.generated Tue Oct 02 12:47:03 CST 2019
     */
    public void setPid(Long pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column history.htime
     *
     * @return the value of history.htime
     *
     * @mbg.generated Tue Oct 02 12:47:03 CST 2019
     */
    public Date getHtime() {
        return htime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column history.htime
     *
     * @param htime the value for history.htime
     *
     * @mbg.generated Tue Oct 02 12:47:03 CST 2019
     */
    public void setHtime(Date htime) {
        this.htime = htime;
    }

    @Override
    public String toString() {
        return "History{" +
                "footList=" + footList +
                ", product=" + product +
                ", hid=" + hid +
                ", uid=" + uid +
                ", pid=" + pid +
                ", htime=" + htime +
                '}';
    }
}